### ISSUE TITLE
Invalid value for table 

### ISSUE THREAD

**Issue by skar404** [m3dev/pptx-template#23]
Invalid value table

### Code: 
```python
ppt = Presentation('in.pptx')
process_all_slides({
        "0": "remove",
        "1": {
            "greeting": {
                "en": "Hello!",
                "ja": "こんにちは！"
            },
            "season": ["Spring", "Summer", "Autumn", "Winter"]
        },
        "2": {
            "bars": {
                "file_name": "chart1.csv",
                "value_axis_max": 150,
                "value_axis_min": 50
            }
        },
        "3": {
            "xy": {}
        },
        "4": {
            "chart": {
                "body": "Season,売り上げ,利益,利益率\n春,100,50,0.5\n夏,110,60,0.5\n秋,120,70,0.5\n冬,130,80,0.6",
                "value_axis_max": 150,
                "value_axis_min": 50
            }
        },
        "5": {
            "table": {
                "body": "Season,売り上げ,利益,利益率\n春,100,50,0.5\n夏,110,60,0.5\n秋,120,70,0.5\n冬,130,80,0.6"
            }
        },
        "pie": {
            "segment": {}
        },
        "nan": {
            "bars": {
                "body": "Season,売り上げ,利益,\n春,100,50,0.5\n,110,60,0.5\n秋,120,70,0.5\n冬,130,80,0.6",
                "value_axis_max": 150,
                "value_axis_min": 50
            }
        }
    }, ppt, True)
ppt.save('out.pptx')
```

### Error:
```python
Invalid value for {table}, model: {'body': 'Season,売り上げ,利益,利益率\n春,100,50,0.5\n夏,110,60,0.5\n秋,120,70,0.5\n冬,130,80,0.6'}
```

![2018-01-23 14 42 06](https://user-images.githubusercontent.com/8483941/35274029-9df8994a-004b-11e8-9a56-74923a571c66.png)

**Comment by reki2000** [comment]
Thanks for rising this issue. unfortunately, this behavior is "correct" for now. I had planned an enhancement for this request as described in !3.

For now, users should write "EL"s for a table as below:
```
| {table.0.0} | {table.0.1} | .....
------------------------------
| {table.1.0} | {table.1.1} | .....
```

**Comment by skar404** [comment]
@reki2000 Ok, at the moment, perhaps stereotyping the table template?  

 {table.0.0} | {table.0.1} 
------------ | -------------
| {table.1.0} | {table.1.1} | 
...|...
| {table.N.0} | {table.N.1} |

and:

 {table.0.0} | {table.0.1}  | ... |  {table.0.N} |
----------- | ----------- | -- | ------------|
| {table.1.0} | {table.1.1} | ... | {table.1.N} |

**Comment by reki2000** [comment]
@skar404 Right. Both are available within N should be less than the size (columns or rows). 

Generally a table template can take:

| {table.0.0} | {table.0.1} | ... | {table.0.N-1} |
|:---:|:---:|:---:|:---:|
|{table.1.0}|{table.1.1}|...|{table.1.N-1}|
|...|...|...|...|
|{table.M-1.0}|{table.M-1.1}|...|{table.M-1.N-1}|

where JSON is 

```
 "table" : { 
    "body" : ..... /// TSV/CSV filename or string, which have M rows and N columns
  }
```
or
```
 "table" : [ 
    [ value_00, value_01, .... ],
    [ value_10, value_11, .... ],
  ]
```

In other words, CSV/TSV can be refered as an 2-dimension array.

**Comment by skar404** [comment]
@reki2000 problem is N and M not known

**Comment by reki2000** [comment]
@skar404 Hmm... sorry, for now pptx-template doesn't support dynamic table resizing. All we can do is to prepare a NxM table with enough large M and N...

**Comment by reki2000** [comment]
Another idea: If you use pptx-template from Python (not CLI), you can access python-pptx objects directly. you can extend table columns/rows via python-pptx's Table object.

This is not a promise, but I might support dynamic resizing while fixing !3
